const GLOBAL = {
  background: '#8fdfff',
  backgroundHell: '#b0e9ff',
  backgroundDunkel: '#5bcefc',
  backgroundDunkeler: '#0898da',
  hover: '#56c5fd',
  fontFamily: "Nunito",
  fontMain: "Cherry Bomb One",
  iconGap: 0.6,
  strokeColor: 'rgba(87, 190, 238, 1)',
  months : [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ],
  days : ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  todaysGoal: 2100,
  cupNum: 1,
  cupAmount: [190,350,600,1000],
}

export { GLOBAL }